schema: "classroom50/repo-config/v1"
classroom: "data-tech-analytics"
assignment: "python-refreshers"
owner:
  username: "JackBaker26"
  id: 233885351
  accepted_at: "2026-09-09T21:43:57Z"
source:
  owner: "IT4063C-Fall2026"
  owner_id: 320344006
  repo: "python-refreshers"
  branch: "main"
